import '../../domain/domain.dart';
import '../models/models.dart';
import 'client_interview_content.dart';
import 'selection_engine.dart';

class ClientInterviewEngine {
  const ClientInterviewEngine._();
  static int _hash(String value){var h=2166136261;for(final c in value.codeUnits){h^=c;h=(h*16777619)&0x7fffffff;}return h;}
  static List<ClientInterviewQuestion> questions({required int seed,required Engineer employee,required Project project,required SkillSheet sheet,int count=3}){
    final candidates=<ClientInterviewQuestionCategory>[ClientInterviewQuestionCategory.technicalExperience,if(project.industry!=Industry.other||sheet.displayedIndustryExperience[project.industry]!=null)ClientInterviewQuestionCategory.industryExperience,if(project.requiredLeader>0||project.requiredManager>0||sheet.displayedLeader>=3||sheet.displayedManager>=3)ClientInterviewQuestionCategory.leadership,ClientInterviewQuestionCategory.roleExperience,ClientInterviewQuestionCategory.communication,ClientInterviewQuestionCategory.teamwork,ClientInterviewQuestionCategory.troubleHandling,ClientInterviewQuestionCategory.workStyle];
    candidates.sort((a,b)=>_score(b,project,sheet,seed).compareTo(_score(a,project,sheet,seed)));
    return candidates.take(count).map((c)=>ClientInterviewQuestion(category:c,text:questionText(c,project,sheet),target:_target(c,project),mismatch:_mismatch(c,employee,project,sheet))).toList();
  }
  static int _score(ClientInterviewQuestionCategory c,Project p,SkillSheet s,int seed){var score=_hash('$seed:${p.id}:${c.name}')%20;switch(c){case ClientInterviewQuestionCategory.technicalExperience:score+=40+(p.requiredLanguages.isNotEmpty?30:0);case ClientInterviewQuestionCategory.industryExperience:score+=20+(s.displayedIndustryExperience[p.industry]??0);case ClientInterviewQuestionCategory.leadership:score+=p.requiredLeader*8+s.displayedLeader*5+p.requiredManager*8;case ClientInterviewQuestionCategory.roleExperience:score+=20+s.displayedRoles.length*10;case ClientInterviewQuestionCategory.communication:score+=p.requiredJapaneseLevel*6;case ClientInterviewQuestionCategory.teamwork:score+=15;case ClientInterviewQuestionCategory.troubleHandling:score+=10;case ClientInterviewQuestionCategory.workStyle:score+=10;}return score;}
  static const _categoryTargetLabels=<ClientInterviewQuestionCategory,String>{ClientInterviewQuestionCategory.technicalExperience:'今回必要な技術領域',ClientInterviewQuestionCategory.industryExperience:'業界知識',ClientInterviewQuestionCategory.leadership:'リーダー経験',ClientInterviewQuestionCategory.roleExperience:'担当領域',ClientInterviewQuestionCategory.communication:'顧客対応',ClientInterviewQuestionCategory.teamwork:'チームでの役割',ClientInterviewQuestionCategory.troubleHandling:'トラブル対応',ClientInterviewQuestionCategory.workStyle:'働き方'};
  static String _target(ClientInterviewQuestionCategory c,Project p)=>c==ClientInterviewQuestionCategory.technicalExperience&&p.requiredLanguages.isNotEmpty?languageName(p.requiredLanguages.first):_categoryTargetLabels[c]!;
  static int _mismatch(ClientInterviewQuestionCategory c,Engineer e,Project p,SkillSheet s){switch(c){case ClientInterviewQuestionCategory.technicalExperience:if(p.requiredLanguages.isEmpty)return 0;final l=p.requiredLanguages.first;return ((s.displayedLanguageExperience[l]??0)-e.profile.skillFor(l).actualExperienceMonths)~/12;case ClientInterviewQuestionCategory.industryExperience:return ((s.displayedIndustryExperience[p.industry]??0)-(e.industryExperience[p.industry]??0))~/12;case ClientInterviewQuestionCategory.leadership:return (s.displayedLeader-e.profile.techSkills.leader).clamp(0,5);case ClientInterviewQuestionCategory.roleExperience:return ((s.displayedLeader-e.profile.techSkills.leader)+(s.displayedManager-e.profile.techSkills.manager)).clamp(0,8);default:return 0;}}
  static String _answerText(ClientInterviewQuestionCategory c,String target,bool vague){if(vague)return '$targetの案件には参加しています。担当範囲はチームで対応することが多く、補助的に経験しました。';return switch(c){ClientInterviewQuestionCategory.technicalExperience=>'$targetを使った開発で、設計から実装・単体試験まで担当しました。課題はチームと確認しながら具体的に解決しました。',ClientInterviewQuestionCategory.industryExperience=>'担当した業務の背景や商習慣を踏まえ、要件を具体的に説明できます。',ClientInterviewQuestionCategory.leadership=>'目的とタスクを整理し、メンバーに役割を割り振りながら進めた経験があります。',ClientInterviewQuestionCategory.roleExperience=>'担当工程を最初から最後まで見届け、判断が必要な場面では自分で決めてきました。',ClientInterviewQuestionCategory.communication=>'要望を丁寧に確認し、認識のズレが出ないよう都度すり合わせながら対応しました。',ClientInterviewQuestionCategory.teamwork=>'チーム内で得意分野を活かし、困っているメンバーがいれば声をかけて助け合ってきました。',ClientInterviewQuestionCategory.troubleHandling=>'問題が起きた際は原因を切り分け、影響範囲を確認したうえで早めに報告・対応しました。',ClientInterviewQuestionCategory.workStyle=>'これまでの現場でも柔軟に環境へ適応し、求められる進め方に合わせてきました。'};}
  static ClientInterviewAnswer answer(Engineer e,Project p,ClientInterviewQuestion q){final comm=e.profile.personality.communication+e.talkSkill+e.profile.hidden.projectInterviewSkill;var actual=3;switch(q.category){case ClientInterviewQuestionCategory.technicalExperience:actual=p.requiredLanguages.isEmpty?e.profile.techSkills.backend:e.profile.skillFor(p.requiredLanguages.first).actualSkill;case ClientInterviewQuestionCategory.industryExperience:actual=((e.industryExperience[p.industry]??0)/12).round().clamp(0,5);case ClientInterviewQuestionCategory.leadership:actual=(e.profile.techSkills.leader+e.profile.techSkills.manager)~/2;default:actual=(comm/3).round().clamp(0,5);}var quality=(actual*12+comm*3-q.mismatch*10+(e.abilities.contains(EmployeeAbility.interviewExpert)?12:0)-(e.abilities.contains(EmployeeAbility.interviewPoor)?12:0)).clamp(5,95);if(e.companyTrust<40&&q.mismatch>0)quality=(quality-5).clamp(5,95);if(e.morale<25)quality=(quality-4).clamp(5,95);final vague=q.mismatch>=2||quality<45;final text=_answerText(q.category,q.target,vague);return ClientInterviewAnswer(text:text,quality:quality,vague:vague);}
  static List<ClientInterviewFollowUp> choices(ClientInterviewQuestion q)=>switch(q.category){ClientInterviewQuestionCategory.technicalExperience=>[ClientInterviewFollowUp.emphasizeTechnical,ClientInterviewFollowUp.adjustExpectation,ClientInterviewFollowUp.letEmployeeHandle],ClientInterviewQuestionCategory.industryExperience=>[ClientInterviewFollowUp.emphasizeIndustry,ClientInterviewFollowUp.emphasizeCommunication,ClientInterviewFollowUp.letEmployeeHandle],ClientInterviewQuestionCategory.leadership=>[ClientInterviewFollowUp.emphasizeLeadership,ClientInterviewFollowUp.adjustExpectation,ClientInterviewFollowUp.letEmployeeHandle],_=>[ClientInterviewFollowUp.emphasizeCommunication,ClientInterviewFollowUp.adjustExpectation,ClientInterviewFollowUp.letEmployeeHandle]};
  static ({int adjustment,bool deepDive,String reaction,ClientInterviewEvaluation evaluation}) evaluate(Engineer e,ClientInterviewQuestion q,ClientInterviewAnswer a,ClientInterviewFollowUp f,int seed,String sessionId){var delta=((a.quality-50)/12).round();var risky=false;switch(f){case ClientInterviewFollowUp.emphasizeTechnical:delta+=q.category==ClientInterviewQuestionCategory.technicalExperience&&q.mismatch==0?3:-2;risky=q.mismatch>=2;case ClientInterviewFollowUp.emphasizeIndustry:delta+=q.category==ClientInterviewQuestionCategory.industryExperience&&q.mismatch==0?3:-2;risky=q.mismatch>=2;case ClientInterviewFollowUp.emphasizeLeadership:final strong=e.profile.techSkills.leader>=3||e.profile.techSkills.manager>=3;delta+=strong?4:-4;risky=!strong;case ClientInterviewFollowUp.emphasizeCommunication:delta+=(e.profile.personality.communication>=4||e.abilities.contains(EmployeeAbility.clientFriendly))?3:1;case ClientInterviewFollowUp.adjustExpectation:delta+=q.mismatch>=2?2:-1;case ClientInterviewFollowUp.letEmployeeHandle:delta+=e.profile.hidden.projectInterviewSkill>=4?2:0;}final deepDive=risky&&_hash('$seed:$sessionId:${q.category.name}:${f.name}')%100<70; if(deepDive)delta-=e.abilities.contains(EmployeeAbility.toughUnderPressure)?2:5;delta=delta.clamp(-5,5);final reaction=deepDive?'面接官は強調された点を、もう少し具体的に確認したいようです。':delta>=3?'面接官は納得しているようです。':delta<=-2?'面接官は少し懸念を持ったようです。':'面接官は回答を受け止め、次の質問へ進みました。';return(adjustment:delta,deepDive:deepDive,reaction:reaction,evaluation:ClientInterviewEvaluation(technical:q.category==ClientInterviewQuestionCategory.technicalExperience?delta:0,experience:a.quality~/20,communication:q.category==ClientInterviewQuestionCategory.communication?delta:1,credibility:q.mismatch>0?-q.mismatch:2,clientFit:e.abilities.contains(EmployeeAbility.clientFriendly)?2:0));}
  static int finalRate(Engineer e,Project p,ClientInterviewSession s,{bool fromInterviewOffer=false,int interviewOfferPenalty=35,SelectionStep step=SelectionStep.clientInterview}){var base=SelectionEngine.successRate(e,p,step);if(fromInterviewOffer)base=(base-interviewOfferPenalty).clamp(5,95);final adjustment=s.accumulatedEvaluation.total.clamp(-15,15);return(base+adjustment).clamp(5,95);}

  /// Codex Broad Review (PR #269) P1: re-derives [session]'s `target`/answer
  /// text from `(category, project)` alone — the exact same pure derivation
  /// [questions]/[answer] use for a brand-new session (see [_target]/
  /// [_answerText]). Never touches category/mismatch (untouched authority
  /// fields on [ClientInterviewQuestion]) or quality/vague (untouched
  /// authority fields on [ClientInterviewAnswer]) — only the two
  /// presentation-only string fields their display text is built from.
  /// Idempotent: a session already generated under the current [_target]
  /// comes back byte-identical, so this is safe to run unconditionally on
  /// every load, not only a session known to carry the pre-fix
  /// [ClientInterviewQuestionCategory] enum-identifier leak.
  static ClientInterviewSession sanitized(ClientInterviewSession session,Project project){
    final questions=[for(final q in session.questions)ClientInterviewQuestion(category:q.category,text:q.text,target:_target(q.category,project),mismatch:q.mismatch)];
    final answers=[for(var i=0;i<session.employeeAnswers.length;i++)ClientInterviewAnswer(text:_answerText(questions[i].category,questions[i].target,session.employeeAnswers[i].vague),quality:session.employeeAnswers[i].quality,vague:session.employeeAnswers[i].vague)];
    return session.copyWith(questions:questions,employeeAnswers:answers);
  }

  /// The one production call site for [sanitized] against a legacy save:
  /// resolves each session's real [Project] via its own `applicationId`
  /// against [proposals] — the same [ProjectProposal] every session was
  /// originally created against (see `GameEngine.startClientInterview`) —
  /// and leaves a session whose proposal can no longer be found (should
  /// never happen for a genuine save) untouched rather than guessing.
  static List<ClientInterviewSession> sanitizeLegacySessions(List<ClientInterviewSession> sessions,List<ProjectProposal> proposals){
    if(sessions.isEmpty)return sessions;
    Project? projectFor(String applicationId){for(final p in proposals){if(p.id==applicationId)return p.project;}return null;}
    return [for(final s in sessions)switch(projectFor(s.applicationId)){final project?=>sanitized(s,project),null=>s}];
  }
}
