import 'package:flutter/material.dart';
import '../../game/public_demo/public_demo_assignment.dart';
import '../../game/public_demo/public_demo_interview.dart';
import '../../game/public_demo/public_demo_recruitment.dart';
import '../../game/public_demo/public_demo_sales.dart';
import '../../game/public_demo/public_demo_state.dart';
import '../asset_paths.dart';
import 'public_demo_event_dialog.dart';
import 'public_demo_interview_result_dialog.dart';
import 'public_demo_sales_progress.dart';
import 'public_demo_salary_offer_dialog.dart';
class PublicDemo01PlaceholderScreen extends StatefulWidget{const PublicDemo01PlaceholderScreen({super.key});@override State<PublicDemo01PlaceholderScreen> createState()=>_S();}
class _S extends State<PublicDemo01PlaceholderScreen>{
 static const expense=800000;PublicDemoState s=PublicDemoState.aprilStart();List<PublicDemoEngineerSales> engineers=publicDemoInitialEngineers;List<PublicDemoApplicant> applicants=publicDemoMayApplicants;List<PublicDemoAssignment> assignments=[];
 void es(int i,PublicDemoSalesStage x)=>setState((){final n=[...engineers];n[i]=n[i].copyWith(stage:x);engineers=n;});void as(int i,PublicDemoApplicantStage x)=>setState((){final n=[...applicants];n[i]=n[i].copyWith(stage:x);applicants=n;});void ars(int i,PublicDemoReplacementStage x)=>setState((){final n=[...assignments];n[i]=n[i].copyWith(replacementStage:x);assignments=n;});
 // Best-effort decode of an event-modal image before its dialog opens, so
 // the first painted frame already has pixels instead of a blank
 // AspectRatio box that pops in and shifts the dialog's layout once decode
 // finishes (investigation report §3C). A decode/network failure (e.g. a
 // corrupt asset) must never block game progression — each dialog's own
 // Image.errorBuilder is the only place that handles the visual fallback,
 // so failures here are swallowed silently.
 // precacheImage() catches its own decode/network errors internally and
 // never rejects the returned Future for them (it resolves the Future
 // regardless, then reports the error via FlutterError.reportError) — a
 // bare try/catch around the await does not see a corrupt asset like
 // order_decision.jpg. Passing `onError` intercepts it at the source
 // instead, so a broken image never surfaces as an unhandled framework
 // error. The outer try/catch only guards truly unexpected synchronous
 // failures (e.g. a bad BuildContext), keeping this best-effort no matter
 // what goes wrong.
 Future<void> _precacheEventImage(String asset)async{if(!mounted)return;try{await precacheImage(AssetImage(asset),context,onError:(exception,stackTrace){});}catch(_){}}
 Future<void> ei(int i,PublicDemoInterviewType t)async{if(t==PublicDemoInterviewType.partner&&s.salesRemaining<=0)return;final e=engineers[i],r=PublicDemoInterviewEvaluator.evaluate(type:t,profile:e.interviewProfile);setState((){if(t==PublicDemoInterviewType.partner)s=s.useSalesSlot();final n=[...engineers];n[i]=e.copyWith(stage:switch((t,r.passed)){(PublicDemoInterviewType.partner,true)=>PublicDemoSalesStage.partnerInterviewPassed,(PublicDemoInterviewType.partner,false)=>PublicDemoSalesStage.partnerInterviewFailed,(PublicDemoInterviewType.client,true)=>PublicDemoSalesStage.clientInterviewPassed,(PublicDemoInterviewType.client,false)=>PublicDemoSalesStage.clientInterviewFailed},lastInterviewScore:r.score);engineers=n;});if(!mounted)return;final partner=t==PublicDemoInterviewType.partner;await _precacheEventImage(AssetPaths.eventClientInterview);if(!mounted)return;await showDialog<void>(context:context,builder:(context)=>PublicDemoInterviewResultDialog(interviewName:partner?'上位会社面談':'客先面談',personName:e.name,score:r.score,passed:r.passed,points:[partner?'経歴・スキルの案件適合度を確認':'技術力と現場での適合度を確認',r.passed?'基準点60点をクリア':'基準点60点に届かず'],nextAction:r.passed?(partner?'次は客先面談へ進みます':'面談通過。案件を受注できます'):'別案件へ再営業しましょう'));}
 // april()/may() used to setState the month advance *before* awaiting the
 // event dialog. showDialog's fade-in transition runs for Material's
 // default 150ms, so for that whole window the ListView behind the modal
 // barrier was already rebuilt for the next month (new cards, new button
 // labels) while the dialog itself was still fading in on top of it — two
 // unrelated text changes animating at once, which on iPhone Safari reads
 // as a momentary garbled/overlapping frame. Reordered so the month
 // (and any state it gates, e.g. `assignments`) is only committed via
 // setState *after* `await showDialog(...)` returns, i.e. after the user
 // has taken the confirm action and the dialog has fully closed — the
 // background never repaints while a dialog transition is in flight. Values
 // captured before the dialog (`o`, `hires`, `ordered`, `nextAssignments`)
 // are pure snapshots of already-settled state, so this only changes when
 // the transition is committed, not what is computed or in what order
 // events fire.
 Future<void> april()async{final o=engineers.where((e)=>e.stage==PublicDemoSalesStage.ordered).length;await _precacheEventImage(AssetPaths.eventRecruitmentApplication);if(!mounted)return;await showDialog<void>(context:context,builder:(context)=>const PublicDemoEventDialog(title:'新しい応募が届きました',imageAsset:AssetPaths.eventRecruitmentApplication,imageKey:Key('public-demo-recruitment-application-image'),message:'採用候補者から応募が届いています。',nextAction:'候補者の経歴書を確認しましょう。'));if(!mounted)return;setState(()=>s=s.advanceToMay(monthlyExpenses:expense,orderedEngineers:o));}void recruit(int i){if(s.salesRemaining<=0)return;setState(()=>s=s.useSalesSlot());as(i,PublicDemoApplicantStage.interviewed);}Future<void> offer(int i)async{final a=applicants[i];final result=await showDialog(context:context,builder:(context)=>PublicDemoSalaryOfferDialog(applicant:a));if(!mounted||result==null)return;as(i,result.accepted?PublicDemoApplicantStage.offerAccepted:PublicDemoApplicantStage.offerDeclined);}
 Future<void> pi(int i)async{if(s.salesRemaining<=0)return;final a=applicants[i];final score=a.salesSkillFit;final passed=score>=60;setState((){s=s.useSalesSlot();final n=[...applicants];n[i]=a.copyWith(stage:passed?PublicDemoApplicantStage.preEntryPartnerPassed:PublicDemoApplicantStage.preEntryPartnerFailed);applicants=n;});if(!mounted)return;await _precacheEventImage(AssetPaths.eventClientInterview);if(!mounted)return;await showDialog<void>(context:context,builder:(context)=>PublicDemoInterviewResultDialog(interviewName:'上位会社面談',personName:a.name,score:score,passed:passed,points:['入社前SkillSheetと案件要件の適合度を確認',passed?'基準点60点をクリア':'基準点60点に届かず'],nextAction:passed?'次は客先面談へ進みます':'別案件へ再営業しましょう'));}
 Future<void> ci(int i)async{final a=applicants[i];final score=a.salesSkillFit;final passed=score>=65;as(i,passed?PublicDemoApplicantStage.preEntryClientPassed:PublicDemoApplicantStage.preEntryClientFailed);if(!mounted)return;await _precacheEventImage(AssetPaths.eventClientInterview);if(!mounted)return;await showDialog<void>(context:context,builder:(context)=>PublicDemoInterviewResultDialog(interviewName:'客先面談',personName:a.name,score:score,passed:passed,points:['入社前の技術力と案件適合度を確認',passed?'入社前営業の通過基準65点をクリア':'入社前営業の通過基準65点に届かず'],nextAction:passed?'面談通過。6月受注へ進めます':'別案件へ再営業しましょう'));}
 bool accepted(PublicDemoApplicant a)=>{PublicDemoApplicantStage.offerAccepted,PublicDemoApplicantStage.preEntrySkillSheet,PublicDemoApplicantStage.preEntrySelling,PublicDemoApplicantStage.preEntryIntroduced,PublicDemoApplicantStage.preEntryPartnerPassed,PublicDemoApplicantStage.preEntryPartnerFailed,PublicDemoApplicantStage.preEntryClientPassed,PublicDemoApplicantStage.preEntryClientFailed,PublicDemoApplicantStage.juneOrdered}.contains(a.stage);
 Future<void> may()async{final hires=applicants.where(accepted).length,ordered=applicants.where((a)=>a.stage==PublicDemoApplicantStage.juneOrdered).length;final first=applicants.where((a)=>a.stage==PublicDemoApplicantStage.juneOrdered).toList();final nextAssignments=[for(final e in engineers)if(e.stage==PublicDemoSalesStage.ordered)publicDemoInitialAssignments.firstWhere((a)=>a.engineerId==e.id),for(final a in applicants)if(a.stage==PublicDemoApplicantStage.juneOrdered)PublicDemoAssignment(engineerId:a.id,engineerName:a.name,projectName:'新規開発支援',deliveryPressure:50,budgetHealth:70,skill:a.salesSkillFit,humanity:70)];if(!mounted)return;if(first.isNotEmpty){await _precacheEventImage(AssetPaths.eventFirstAssignment);if(!mounted)return;await showDialog<void>(context:context,builder:(context)=>PublicDemoEventDialog(title:'入社・初参画！',imageAsset:AssetPaths.eventFirstAssignment,imageKey:const Key('public-demo-first-assignment-image'),message:'${first.first.name}さんが入社し、案件への参画を開始しました。',nextAction:'参画中メンバーの翌月発注を確認しましょう。'));if(!mounted)return;}setState((){s=s.advanceToJune(monthlyExpenses:expense,acceptedHires:hires,hiredWithOrders:ordered);assignments=nextAssignments;});}
 void decideOrder(int i){final a=assignments[i];setState((){final n=[...assignments];n[i]=a.copyWith(nextOrderStatus:a.willOfferNextMonth?PublicDemoNextOrderStatus.offered:PublicDemoNextOrderStatus.notOffered);assignments=n;});}void acceptOrder(int i){setState((){final n=[...assignments];n[i]=n[i].copyWith(nextOrderStatus:PublicDemoNextOrderStatus.accepted);assignments=n;});}void replacementPartner(int i){if(s.salesRemaining<=0)return;final a=assignments[i];setState((){s=s.useSalesSlot();final n=[...assignments];n[i]=a.copyWith(replacementStage:a.replacementPartnerScore>=60?PublicDemoReplacementStage.partnerPassed:PublicDemoReplacementStage.partnerFailed);assignments=n;});}void replacementClient(int i){final a=assignments[i];ars(i,a.replacementClientScore>=60?PublicDemoReplacementStage.clientPassed:PublicDemoReplacementStage.clientFailed);}
 void june(){final assigned=assignments.where((a)=>a.nextOrderStatus==PublicDemoNextOrderStatus.accepted||a.replacementStage==PublicDemoReplacementStage.ordered).length;setState(()=>s=s.advanceToJuly(monthlyExpenses:expense,assignedInJuly:assigned));}
 String julyResult(PublicDemoAssignment a){if(a.nextOrderStatus==PublicDemoNextOrderStatus.accepted)return'現案件を継続';if(a.replacementStage==PublicDemoReplacementStage.ordered)return'新案件へ切替';return'待機（営業が必要）';}
 String engineerStatus(PublicDemoEngineerSales e)=>switch(e.stage){PublicDemoSalesStage.waiting=>'待機',PublicDemoSalesStage.skillSheet=>'営業準備',PublicDemoSalesStage.selling=>'営業中',PublicDemoSalesStage.introduced=>'案件紹介済',PublicDemoSalesStage.partnerInterviewPassed=>'上位面談通過',PublicDemoSalesStage.partnerInterviewFailed=>'上位面談不合格',PublicDemoSalesStage.clientInterviewPassed=>'客先面談通過',PublicDemoSalesStage.clientInterviewFailed=>'客先面談不合格',PublicDemoSalesStage.ordered=>'翌月参画予定'};
 int engineerStep(PublicDemoEngineerSales e)=>switch(e.stage){PublicDemoSalesStage.waiting||PublicDemoSalesStage.skillSheet=>0,PublicDemoSalesStage.selling=>1,PublicDemoSalesStage.introduced=>2,PublicDemoSalesStage.partnerInterviewPassed||PublicDemoSalesStage.partnerInterviewFailed=>3,PublicDemoSalesStage.clientInterviewPassed||PublicDemoSalesStage.clientInterviewFailed=>4,PublicDemoSalesStage.ordered=>5};
 String applicantStatus(PublicDemoApplicant a)=>switch(a.stage){PublicDemoApplicantStage.applied=>'応募',PublicDemoApplicantStage.resumeReviewed=>'書類確認済',PublicDemoApplicantStage.interviewed=>'採用面談済',PublicDemoApplicantStage.rejected=>'不採用',PublicDemoApplicantStage.offerAccepted=>'内定承諾',PublicDemoApplicantStage.offerDeclined=>'内定辞退',PublicDemoApplicantStage.preEntrySkillSheet=>'入社前営業準備',PublicDemoApplicantStage.preEntrySelling=>'入社前営業中',PublicDemoApplicantStage.preEntryIntroduced=>'案件紹介済',PublicDemoApplicantStage.preEntryPartnerPassed=>'上位面談通過',PublicDemoApplicantStage.preEntryPartnerFailed=>'上位面談不合格',PublicDemoApplicantStage.preEntryClientPassed=>'客先面談通過',PublicDemoApplicantStage.preEntryClientFailed=>'客先面談不合格',PublicDemoApplicantStage.juneOrdered=>'入社・参画予定'};
 int applicantStep(PublicDemoApplicant a)=>switch(a.stage){PublicDemoApplicantStage.applied||PublicDemoApplicantStage.resumeReviewed||PublicDemoApplicantStage.interviewed||PublicDemoApplicantStage.rejected||PublicDemoApplicantStage.offerAccepted||PublicDemoApplicantStage.offerDeclined||PublicDemoApplicantStage.preEntrySkillSheet=>0,PublicDemoApplicantStage.preEntrySelling=>1,PublicDemoApplicantStage.preEntryIntroduced=>2,PublicDemoApplicantStage.preEntryPartnerPassed||PublicDemoApplicantStage.preEntryPartnerFailed=>3,PublicDemoApplicantStage.preEntryClientPassed||PublicDemoApplicantStage.preEntryClientFailed=>4,PublicDemoApplicantStage.juneOrdered=>5};
 String monthGoal()=>switch(s.month){4=>'待機中の技術者を営業し、5月の案件参画を決めましょう',5=>'応募者を採用し、入社前から6月の案件獲得を目指しましょう',6=>'翌月の発注を確認し、7月も稼働できる状態を作りましょう',_=>'4〜6月の経営結果を確認しましょう'};
 Widget stat(String label,String value)=>Expanded(child:Card(child:Padding(padding:const EdgeInsets.symmetric(vertical:10,horizontal:6),child:Column(children:[Text(value,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:17)),Text(label,style:const TextStyle(fontSize:11))]))));
 Widget dashboard()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('今月やること',style:TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:4),Text(monthGoal())]))),Row(children:[stat('現預金','¥${(s.cash/10000).floor()}万'),stat('参画','${s.engineersAssigned}名'),stat('待機','${s.engineersWaiting}名'),stat('営業残','${s.salesRemaining}回')]),const SizedBox(height:8)]);
 Widget badge(String text)=>Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:4),decoration:BoxDecoration(color:Theme.of(context).colorScheme.secondaryContainer,borderRadius:BorderRadius.circular(20)),child:Text(text,style:const TextStyle(fontSize:12,fontWeight:FontWeight.bold)));
 Widget assignmentCard(int i){final a=assignments[i];return Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(a.engineerName,style:const TextStyle(fontWeight:FontWeight.bold)),badge(a.nextOrderStatus==PublicDemoNextOrderStatus.accepted?'継続予定':'参画中')]),Text(a.projectName),if(a.nextOrderStatus==PublicDemoNextOrderStatus.undecided)FilledButton.tonal(onPressed:()=>decideOrder(i),child:const Text('7月分の発注を確認')),if(a.nextOrderStatus==PublicDemoNextOrderStatus.offered)...[const Text('7月分発注あり'),FilledButton(onPressed:()=>acceptOrder(i),child:const Text('受注する'))],if(a.nextOrderStatus==PublicDemoNextOrderStatus.accepted)const Text('7月：現案件継続予定'),if(a.nextOrderStatus==PublicDemoNextOrderStatus.notOffered)...[const Text('7月分発注なし'),if(a.replacementStage==PublicDemoReplacementStage.none)FilledButton(onPressed:()=>ars(i,PublicDemoReplacementStage.selling),child:const Text('次案件の営業開始')),if(a.replacementStage==PublicDemoReplacementStage.selling)FilledButton.tonal(onPressed:()=>ars(i,PublicDemoReplacementStage.introduced),child:const Text('案件紹介')),if(a.replacementStage==PublicDemoReplacementStage.introduced)FilledButton(onPressed:s.salesRemaining>0?()=>replacementPartner(i):null,child:const Text('上位会社面談（1枠）')),if(a.replacementStage==PublicDemoReplacementStage.partnerPassed)FilledButton.tonal(onPressed:()=>replacementClient(i),child:const Text('客先面談（0枠）')),if(a.replacementStage==PublicDemoReplacementStage.partnerFailed||a.replacementStage==PublicDemoReplacementStage.clientFailed)FilledButton.tonal(onPressed:()=>ars(i,PublicDemoReplacementStage.selling),child:const Text('別案件へ')),if(a.replacementStage==PublicDemoReplacementStage.clientPassed)FilledButton(onPressed:()=>ars(i,PublicDemoReplacementStage.ordered),child:const Text('7月分を受注')),if(a.replacementStage==PublicDemoReplacementStage.ordered)const Text('7月：新案件参画予定')]])));}
 Widget ec(int i){final e=engineers[i];return Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(e.name,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:16)),badge(engineerStatus(e))]),const SizedBox(height:4),Text(e.summary),PublicDemoSalesProgress(currentStep:engineerStep(e)),const SizedBox(height:8),if(e.stage==PublicDemoSalesStage.waiting)FilledButton(onPressed:()=>es(i,PublicDemoSalesStage.skillSheet),child:const Text('SkillSheet確認')),if(e.stage==PublicDemoSalesStage.skillSheet)FilledButton(onPressed:()=>es(i,PublicDemoSalesStage.selling),child:const Text('営業開始')),if(e.stage==PublicDemoSalesStage.selling)FilledButton(onPressed:()=>es(i,PublicDemoSalesStage.introduced),child:const Text('案件紹介')),if(e.stage==PublicDemoSalesStage.introduced)FilledButton(onPressed:s.salesRemaining>0?()=>ei(i,PublicDemoInterviewType.partner):null,child:const Text('上位会社面談')),if(e.stage==PublicDemoSalesStage.partnerInterviewPassed)FilledButton(onPressed:()=>ei(i,PublicDemoInterviewType.client),child:const Text('客先面談')),if(e.stage==PublicDemoSalesStage.clientInterviewPassed)FilledButton(onPressed:()async{es(i,PublicDemoSalesStage.ordered);if(!mounted)return;await _precacheEventImage(AssetPaths.eventOrderDecision);if(!mounted)return;await showDialog<void>(context:context,builder:(context)=>PublicDemoEventDialog(title:'案件を受注しました',imageAsset:AssetPaths.eventOrderDecision,imageKey:const Key('public-demo-order-decision-image'),message:'${e.name}さんの5月分案件を受注しました。',nextAction:'翌月からの参画に備え、残りの営業状況も確認しましょう。'));},child:const Text('受注')),if(e.stage==PublicDemoSalesStage.partnerInterviewFailed||e.stage==PublicDemoSalesStage.clientInterviewFailed)FilledButton(onPressed:()=>es(i,PublicDemoSalesStage.selling),child:const Text('再営業'))])));}
 Widget ac(int i){final a=applicants[i];return Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(a.name,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:16)),badge(applicantStatus(a))]),const SizedBox(height:4),Text(a.resumeSummary),if(accepted(a))PublicDemoSalesProgress(currentStep:applicantStep(a),preEntry:true),const SizedBox(height:8),if(a.stage==PublicDemoApplicantStage.applied)FilledButton(onPressed:()=>as(i,PublicDemoApplicantStage.resumeReviewed),child:const Text('経歴書確認')),if(a.stage==PublicDemoApplicantStage.resumeReviewed)FilledButton(onPressed:s.salesRemaining>0?()=>recruit(i):null,child:const Text('採用面談')),if(a.stage==PublicDemoApplicantStage.interviewed)...[Text('評価 ${a.interviewScore}'),Text('希望給与 ${a.requestedMonthlySalary~/10000}万円'),FilledButton(onPressed:a.interviewScore>=60?()=>offer(i):null,child:const Text('合格・給与提示'))],if(a.stage==PublicDemoApplicantStage.offerAccepted)FilledButton(onPressed:()=>as(i,PublicDemoApplicantStage.preEntrySkillSheet),child:const Text('入社前SkillSheet')),if(a.stage==PublicDemoApplicantStage.preEntrySkillSheet)FilledButton(onPressed:()=>as(i,PublicDemoApplicantStage.preEntrySelling),child:const Text('入社前営業')),if(a.stage==PublicDemoApplicantStage.preEntrySelling)FilledButton(onPressed:()=>as(i,PublicDemoApplicantStage.preEntryIntroduced),child:const Text('案件紹介')),if(a.stage==PublicDemoApplicantStage.preEntryIntroduced)FilledButton(onPressed:s.salesRemaining>0?()=>pi(i):null,child:const Text('上位会社面談')),if(a.stage==PublicDemoApplicantStage.preEntryPartnerPassed)FilledButton(onPressed:()=>ci(i),child:const Text('客先面談')),if(a.stage==PublicDemoApplicantStage.preEntryClientPassed)FilledButton(onPressed:()async{as(i,PublicDemoApplicantStage.juneOrdered);if(!mounted)return;await _precacheEventImage(AssetPaths.eventOrderDecision);if(!mounted)return;await showDialog<void>(context:context,builder:(context)=>PublicDemoEventDialog(title:'案件を受注しました',imageAsset:AssetPaths.eventOrderDecision,imageKey:const Key('public-demo-order-decision-image'),message:'${a.name}さんの6月分案件を受注しました。',nextAction:'入社と初参画に向けて6月へ進みましょう。'));},child:const Text('6月受注'))])));}
 // The app-wide FilledButton theme (lib/ui/theme.dart) sets only
 // `vertical: 14` padding, which zeroes out the horizontal padding
 // (EdgeInsets.symmetric defaults an omitted side to 0) instead of leaving
 // Material 3's own default (24) in place. Every stage-action button in
 // Public Demo (SkillSheet確認, 営業開始, 上位会社面談, 客先面談（0枠）, ...)
 // is a FilledButton/FilledButton.tonal that shrink-wraps its content, so
 // that theme bug reads as cramped, edge-to-edge label text rather than an
 // actual clip — worst on the longer Japanese labels. Fixed locally here
 // (rather than in the shared theme) to keep this change scoped to Public
 // Demo, as requested, instead of restyling every button in the app.
 // Vertical padding (and with it the >=48dp tap target) is left untouched.
 ButtonStyle? _publicDemoFilledButtonStyle(BuildContext c)=>Theme.of(c).filledButtonTheme.style?.copyWith(padding:const WidgetStatePropertyAll(EdgeInsets.symmetric(horizontal:20,vertical:14)));
 @override Widget build(BuildContext c)=>Theme(data:Theme.of(c).copyWith(filledButtonTheme:FilledButtonThemeData(style:_publicDemoFilledButtonStyle(c))),child:Scaffold(appBar:AppBar(title:const Text('S.E.S. Public Demo 0.1')),body:SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[Text('${s.month}月',style:Theme.of(c).textTheme.headlineMedium),dashboard(),if(s.month==4)...[for(var i=0;i<engineers.length;i++)ec(i),OutlinedButton(onPressed:april,child:const Text('4月終了→5月'))],if(s.month==5)...[for(var i=0;i<applicants.length;i++)ac(i),OutlinedButton(onPressed:may,child:const Text('5月終了→6月'))],if(s.month==6)...[for(var i=0;i<assignments.length;i++)assignmentCard(i),OutlinedButton(onPressed:june,child:const Text('6月終了→7月'))],if(s.month==7)...[Text('7月開始結果',style:Theme.of(c).textTheme.titleLarge),Text('参画 ${s.engineersAssigned}名 / 待機 ${s.engineersWaiting}名'),for(final a in assignments)ListTile(title:Text(a.engineerName),subtitle:Text(julyResult(a)))]]))));
}
