import 'package:flutter/material.dart';
import '../../game/public_demo/public_demo_interview.dart';
import '../../game/public_demo/public_demo_recruitment.dart';
import '../../game/public_demo/public_demo_sales.dart';
import '../../game/public_demo/public_demo_state.dart';

class PublicDemo01PlaceholderScreen extends StatefulWidget{const PublicDemo01PlaceholderScreen({super.key});@override State<PublicDemo01PlaceholderScreen> createState()=>_S();}
class _S extends State<PublicDemo01PlaceholderScreen>{
 static const expense=800000; PublicDemoState s=PublicDemoState.aprilStart(); List<PublicDemoEngineerSales> engineers=publicDemoInitialEngineers; List<PublicDemoApplicant> applicants=publicDemoMayApplicants;
 void es(int i,PublicDemoSalesStage x)=>setState((){final n=[...engineers];n[i]=n[i].copyWith(stage:x);engineers=n;}); void as(int i,PublicDemoApplicantStage x)=>setState((){final n=[...applicants];n[i]=n[i].copyWith(stage:x);applicants=n;});
 void ei(int i,PublicDemoInterviewType t){if(t==PublicDemoInterviewType.partner&&s.salesRemaining<=0)return;final e=engineers[i],r=PublicDemoInterviewEvaluator.evaluate(type:t,profile:e.interviewProfile);setState((){if(t==PublicDemoInterviewType.partner)s=s.useSalesSlot();final n=[...engineers];n[i]=e.copyWith(stage:switch((t,r.passed)){(PublicDemoInterviewType.partner,true)=>PublicDemoSalesStage.partnerInterviewPassed,(PublicDemoInterviewType.partner,false)=>PublicDemoSalesStage.partnerInterviewFailed,(PublicDemoInterviewType.client,true)=>PublicDemoSalesStage.clientInterviewPassed,(PublicDemoInterviewType.client,false)=>PublicDemoSalesStage.clientInterviewFailed},lastInterviewScore:r.score);engineers=n;});}
 void april(){final o=engineers.where((e)=>e.stage==PublicDemoSalesStage.ordered).length;setState(()=>s=s.advanceToMay(monthlyExpenses:expense,orderedEngineers:o));}
 void recruit(int i){if(s.salesRemaining<=0)return;setState(()=>s=s.useSalesSlot());as(i,PublicDemoApplicantStage.interviewed);} void offer(int i){final a=applicants[i];as(i,a.acceptanceScore>=60?PublicDemoApplicantStage.offerAccepted:PublicDemoApplicantStage.offerDeclined);}
 void pi(int i){if(s.salesRemaining<=0)return;final a=applicants[i];setState((){s=s.useSalesSlot();final n=[...applicants];n[i]=a.copyWith(stage:a.salesSkillFit>=60?PublicDemoApplicantStage.preEntryPartnerPassed:PublicDemoApplicantStage.preEntryPartnerFailed);applicants=n;});} void ci(int i){as(i,applicants[i].salesSkillFit>=65?PublicDemoApplicantStage.preEntryClientPassed:PublicDemoApplicantStage.preEntryClientFailed);}
 bool accepted(PublicDemoApplicant a)=>{PublicDemoApplicantStage.offerAccepted,PublicDemoApplicantStage.preEntrySkillSheet,PublicDemoApplicantStage.preEntrySelling,PublicDemoApplicantStage.preEntryIntroduced,PublicDemoApplicantStage.preEntryPartnerPassed,PublicDemoApplicantStage.preEntryPartnerFailed,PublicDemoApplicantStage.preEntryClientPassed,PublicDemoApplicantStage.preEntryClientFailed,PublicDemoApplicantStage.juneOrdered}.contains(a.stage);
 void may(){final hires=applicants.where(accepted).length,ordered=applicants.where((a)=>a.stage==PublicDemoApplicantStage.juneOrdered).length;setState(()=>s=s.advanceToJune(monthlyExpenses:expense,acceptedHires:hires,hiredWithOrders:ordered));}
 Widget ec(int i){final e=engineers[i],f=e.stage==PublicDemoSalesStage.partnerInterviewFailed||e.stage==PublicDemoSalesStage.clientInterviewFailed;return Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(e.name),Text(e.summary),Text(e.stage.name),if(e.stage==PublicDemoSalesStage.waiting)FilledButton.tonal(onPressed:()=>es(i,PublicDemoSalesStage.skillSheet),child:const Text('SkillSheet確認')),if(e.stage==PublicDemoSalesStage.skillSheet)FilledButton(onPressed:()=>es(i,PublicDemoSalesStage.selling),child:const Text('営業開始')),if(e.stage==PublicDemoSalesStage.selling)FilledButton.tonal(onPressed:()=>es(i,PublicDemoSalesStage.introduced),child:const Text('案件紹介')),if(e.stage==PublicDemoSalesStage.introduced)FilledButton(onPressed:s.salesRemaining>0?()=>ei(i,PublicDemoInterviewType.partner):null,child:const Text('上位会社面談（1枠）')),if(e.stage==PublicDemoSalesStage.partnerInterviewPassed)FilledButton.tonal(onPressed:()=>ei(i,PublicDemoInterviewType.client),child:const Text('客先面談')),if(e.stage==PublicDemoSalesStage.clientInterviewPassed)FilledButton(onPressed:()=>es(i,PublicDemoSalesStage.ordered),child:const Text('翌月発注を受注')),if(f)FilledButton.tonal(onPressed:()=>es(i,PublicDemoSalesStage.selling),child:const Text('別案件へ'))])));}
 Widget ac(int i){final a=applicants[i];return Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a.name),Text(a.resumeSummary),Text(a.stage.name),if(a.stage==PublicDemoApplicantStage.applied)FilledButton.tonal(onPressed:()=>as(i,PublicDemoApplicantStage.resumeReviewed),child:const Text('経歴書確認')),if(a.stage==PublicDemoApplicantStage.resumeReviewed)FilledButton(onPressed:s.salesRemaining>0?()=>recruit(i):null,child:const Text('採用面談（1枠）')),if(a.stage==PublicDemoApplicantStage.interviewed)...[Text('面談評価 ${a.interviewScore}'),FilledButton(onPressed:a.interviewScore>=60?()=>offer(i):null,child:const Text('合格・内定')),OutlinedButton(onPressed:()=>as(i,PublicDemoApplicantStage.rejected),child:const Text('不採用'))],if(a.stage==PublicDemoApplicantStage.offerAccepted)FilledButton.tonal(onPressed:()=>as(i,PublicDemoApplicantStage.preEntrySkillSheet),child:const Text('入社前SkillSheet')),if(a.stage==PublicDemoApplicantStage.preEntrySkillSheet)FilledButton(onPressed:()=>as(i,PublicDemoApplicantStage.preEntrySelling),child:const Text('入社前営業')),if(a.stage==PublicDemoApplicantStage.preEntrySelling)FilledButton.tonal(onPressed:()=>as(i,PublicDemoApplicantStage.preEntryIntroduced),child:const Text('6月案件紹介')),if(a.stage==PublicDemoApplicantStage.preEntryIntroduced)FilledButton(onPressed:s.salesRemaining>0?()=>pi(i):null,child:const Text('上位会社面談（1枠）')),if(a.stage==PublicDemoApplicantStage.preEntryPartnerPassed)FilledButton.tonal(onPressed:()=>ci(i),child:const Text('客先面談（0枠）')),if(a.stage==PublicDemoApplicantStage.preEntryPartnerFailed||a.stage==PublicDemoApplicantStage.preEntryClientFailed)FilledButton.tonal(onPressed:()=>as(i,PublicDemoApplicantStage.preEntrySelling),child:const Text('別案件へ')),if(a.stage==PublicDemoApplicantStage.preEntryClientPassed)FilledButton(onPressed:()=>as(i,PublicDemoApplicantStage.juneOrdered),child:const Text('6月発注を受注')),if(a.stage==PublicDemoApplicantStage.juneOrdered)const Text('6月：入社＋参画予定')])));}
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('S.E.S. Public Demo 0.1')),body:SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[Text('${s.month}月',style:Theme.of(c).textTheme.headlineMedium),Card(child:Padding(padding:const EdgeInsets.all(12),child:Text('現預金 ¥${s.cash}\n技術者 ${s.engineerCount}名 / 総務 ${s.adminCount}名\n参画 ${s.engineersAssigned}名 / 待機 ${s.engineersWaiting}名\n営業 ${s.salesUsed}/${s.salesCapacity}（残${s.salesRemaining}）'))),if(s.month==4)...[for(var i=0;i<engineers.length;i++)ec(i),OutlinedButton(onPressed:april,child:const Text('4月終了→5月'))]else if(s.month==5)...[Text('応募者',style:Theme.of(c).textTheme.titleLarge),for(var i=0;i<applicants.length;i++)ac(i),OutlinedButton(onPressed:may,child:const Text('5月終了→6月'))]else...[Text('6月開始',style:Theme.of(c).textTheme.titleLarge),Text('正式在籍：技術者 ${s.engineerCount}名'),Text('案件参画：${s.engineersAssigned}名 / 待機：${s.engineersWaiting}名'),const Text('営業枠は4枠にリセット。'),for(final a in applicants)if(accepted(a))ListTile(title:Text(a.name),subtitle:Text(a.stage==PublicDemoApplicantStage.juneOrdered?'6月入社・案件参画':'6月入社・待機'))]])));
}
