import 'package:flutter/material.dart';
import '../../game/public_demo/public_demo_assignment.dart';
import '../../game/public_demo/public_demo_interview.dart';
import '../../game/public_demo/public_demo_recruitment.dart';
import '../../game/public_demo/public_demo_sales.dart';
import '../../game/public_demo/public_demo_state.dart';
class PublicDemo01PlaceholderScreen extends StatefulWidget{const PublicDemo01PlaceholderScreen({super.key});@override State<PublicDemo01PlaceholderScreen> createState()=>_S();}
class _S extends State<PublicDemo01PlaceholderScreen>{
 static const expense=800000;PublicDemoState s=PublicDemoState.aprilStart();List<PublicDemoEngineerSales> engineers=publicDemoInitialEngineers;List<PublicDemoApplicant> applicants=publicDemoMayApplicants;List<PublicDemoAssignment> assignments=[];
 void es(int i,PublicDemoSalesStage x)=>setState((){final n=[...engineers];n[i]=n[i].copyWith(stage:x);engineers=n;});void as(int i,PublicDemoApplicantStage x)=>setState((){final n=[...applicants];n[i]=n[i].copyWith(stage:x);applicants=n;});void ars(int i,PublicDemoReplacementStage x)=>setState((){final n=[...assignments];n[i]=n[i].copyWith(replacementStage:x);assignments=n;});
 void ei(int i,PublicDemoInterviewType t){if(t==PublicDemoInterviewType.partner&&s.salesRemaining<=0)return;final e=engineers[i],r=PublicDemoInterviewEvaluator.evaluate(type:t,profile:e.interviewProfile);setState((){if(t==PublicDemoInterviewType.partner)s=s.useSalesSlot();final n=[...engineers];n[i]=e.copyWith(stage:switch((t,r.passed)){(PublicDemoInterviewType.partner,true)=>PublicDemoSalesStage.partnerInterviewPassed,(PublicDemoInterviewType.partner,false)=>PublicDemoSalesStage.partnerInterviewFailed,(PublicDemoInterviewType.client,true)=>PublicDemoSalesStage.clientInterviewPassed,(PublicDemoInterviewType.client,false)=>PublicDemoSalesStage.clientInterviewFailed},lastInterviewScore:r.score);engineers=n;});}
 void april(){final o=engineers.where((e)=>e.stage==PublicDemoSalesStage.ordered).length;setState(()=>s=s.advanceToMay(monthlyExpenses:expense,orderedEngineers:o));}void recruit(int i){if(s.salesRemaining<=0)return;setState(()=>s=s.useSalesSlot());as(i,PublicDemoApplicantStage.interviewed);}void offer(int i){final a=applicants[i];as(i,a.acceptanceScore>=60?PublicDemoApplicantStage.offerAccepted:PublicDemoApplicantStage.offerDeclined);}
 void pi(int i){if(s.salesRemaining<=0)return;final a=applicants[i];setState((){s=s.useSalesSlot();final n=[...applicants];n[i]=a.copyWith(stage:a.salesSkillFit>=60?PublicDemoApplicantStage.preEntryPartnerPassed:PublicDemoApplicantStage.preEntryPartnerFailed);applicants=n;});}void ci(int i){as(i,applicants[i].salesSkillFit>=65?PublicDemoApplicantStage.preEntryClientPassed:PublicDemoApplicantStage.preEntryClientFailed);}
 bool accepted(PublicDemoApplicant a)=>{PublicDemoApplicantStage.offerAccepted,PublicDemoApplicantStage.preEntrySkillSheet,PublicDemoApplicantStage.preEntrySelling,PublicDemoApplicantStage.preEntryIntroduced,PublicDemoApplicantStage.preEntryPartnerPassed,PublicDemoApplicantStage.preEntryPartnerFailed,PublicDemoApplicantStage.preEntryClientPassed,PublicDemoApplicantStage.preEntryClientFailed,PublicDemoApplicantStage.juneOrdered}.contains(a.stage);
 void may(){final hires=applicants.where(accepted).length,ordered=applicants.where((a)=>a.stage==PublicDemoApplicantStage.juneOrdered).length;setState((){s=s.advanceToJune(monthlyExpenses:expense,acceptedHires:hires,hiredWithOrders:ordered);assignments=[for(final e in engineers)if(e.stage==PublicDemoSalesStage.ordered)publicDemoInitialAssignments.firstWhere((a)=>a.engineerId==e.id),for(final a in applicants)if(a.stage==PublicDemoApplicantStage.juneOrdered)PublicDemoAssignment(engineerId:a.id,engineerName:a.name,projectName:'新規開発支援',deliveryPressure:50,budgetHealth:70,skill:a.salesSkillFit,humanity:70)];});}
 void decideOrder(int i){final a=assignments[i];setState((){final n=[...assignments];n[i]=a.copyWith(nextOrderStatus:a.willOfferNextMonth?PublicDemoNextOrderStatus.offered:PublicDemoNextOrderStatus.notOffered);assignments=n;});}void acceptOrder(int i){setState((){final n=[...assignments];n[i]=n[i].copyWith(nextOrderStatus:PublicDemoNextOrderStatus.accepted);assignments=n;});}void replacementPartner(int i){if(s.salesRemaining<=0)return;final a=assignments[i];setState((){s=s.useSalesSlot();final n=[...assignments];n[i]=a.copyWith(replacementStage:a.replacementPartnerScore>=60?PublicDemoReplacementStage.partnerPassed:PublicDemoReplacementStage.partnerFailed);assignments=n;});}void replacementClient(int i){final a=assignments[i];ars(i,a.replacementClientScore>=60?PublicDemoReplacementStage.clientPassed:PublicDemoReplacementStage.clientFailed);}
 void june(){final assigned=assignments.where((a)=>a.nextOrderStatus==PublicDemoNextOrderStatus.accepted||a.replacementStage==PublicDemoReplacementStage.ordered).length;setState(()=>s=s.advanceToJuly(monthlyExpenses:expense,assignedInJuly:assigned));}
 String julyResult(PublicDemoAssignment a){if(a.nextOrderStatus==PublicDemoNextOrderStatus.accepted)return'現案件を継続';if(a.replacementStage==PublicDemoReplacementStage.ordered)return'新案件へ切替';return'待機（営業が必要）';}
 String engineerStatus(PublicDemoEngineerSales e)=>switch(e.stage){PublicDemoSalesStage.waiting=>'待機',PublicDemoSalesStage.skillSheet=>'営業準備',PublicDemoSalesStage.selling=>'営業中',PublicDemoSalesStage.introduced=>'案件紹介済',PublicDemoSalesStage.partnerInterviewPassed=>'上位面談通過',PublicDemoSalesStage.partnerInterviewFailed=>'上位面談不合格',PublicDemoSalesStage.clientInterviewPassed=>'客先面談通過',PublicDemoSalesStage.clientInterviewFailed=>'客先面談不合格',PublicDemoSalesStage.ordered=>'翌月参画予定'};
 String applicantStatus(PublicDemoApplicant a)=>switch(a.stage){PublicDemoApplicantStage.applied=>'応募',PublicDemoApplicantStage.resumeReviewed=>'書類確認済',PublicDemoApplicantStage.interviewed=>'採用面談済',PublicDemoApplicantStage.offerAccepted=>'内定承諾',PublicDemoApplicantStage.offerDeclined=>'内定辞退',PublicDemoApplicantStage.preEntrySkillSheet=>'入社前営業準備',PublicDemoApplicantStage.preEntrySelling=>'入社前営業中',PublicDemoApplicantStage.preEntryIntroduced=>'案件紹介済',PublicDemoApplicantStage.preEntryPartnerPassed=>'上位面談通過',PublicDemoApplicantStage.preEntryPartnerFailed=>'上位面談不合格',PublicDemoApplicantStage.preEntryClientPassed=>'客先面談通過',PublicDemoApplicantStage.preEntryClientFailed=>'客先面談不合格',PublicDemoApplicantStage.juneOrdered=>'入社・参画予定'};
 String monthGoal()=>switch(s.month){4=>'待機中の技術者を営業し、5月の案件参画を決めましょう',5=>'応募者を採用し、入社前から6月の案件獲得を目指しましょう',6=>'翌月の発注を確認し、7月も稼働できる状態を作りましょう',_=>'4〜6月の経営結果を確認しましょう'};
 Widget stat(String label,String value)=>Expanded(child:Card(child:Padding(padding:const EdgeInsets.symmetric(vertical:10,horizontal:6),child:Column(children:[Text(value,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:17)),Text(label,style:const TextStyle(fontSize:11))]))));
 Widget dashboard()=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('今月やること',style:TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:4),Text(monthGoal())]))),Row(children:[stat('現預金','¥${(s.cash/10000).floor()}万'),stat('参画','${s.engineersAssigned}名'),stat('待機','${s.engineersWaiting}名'),stat('営業残','${s.salesRemaining}回')]),const SizedBox(height:8)]);
 Widget badge(String text)=>Container(padding:const EdgeInsets.symmetric(horizontal:10,vertical:4),decoration:BoxDecoration(color:Theme.of(context).colorScheme.secondaryContainer,borderRadius:BorderRadius.circular(20)),child:Text(text,style:const TextStyle(fontSize:12,fontWeight:FontWeight.bold)));
 Widget assignmentCard(int i){final a=assignments[i];return Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(a.engineerName,style:const TextStyle(fontWeight:FontWeight.bold)),badge(a.nextOrderStatus==PublicDemoNextOrderStatus.accepted?'継続予定':'参画中')]),Text(a.projectName),if(a.nextOrderStatus==PublicDemoNextOrderStatus.undecided)FilledButton.tonal(onPressed:()=>decideOrder(i),child:const Text('7月分の発注を確認')),if(a.nextOrderStatus==PublicDemoNextOrderStatus.offered)...[const Text('7月分発注あり'),FilledButton(onPressed:()=>acceptOrder(i),child:const Text('受注する'))],if(a.nextOrderStatus==PublicDemoNextOrderStatus.accepted)const Text('7月：現案件継続予定'),if(a.nextOrderStatus==PublicDemoNextOrderStatus.notOffered)...[const Text('7月分発注なし'),if(a.replacementStage==PublicDemoReplacementStage.none)FilledButton(onPressed:()=>ars(i,PublicDemoReplacementStage.selling),child:const Text('次案件の営業開始')),if(a.replacementStage==PublicDemoReplacementStage.selling)FilledButton.tonal(onPressed:()=>ars(i,PublicDemoReplacementStage.introduced),child:const Text('案件紹介')),if(a.replacementStage==PublicDemoReplacementStage.introduced)FilledButton(onPressed:s.salesRemaining>0?()=>replacementPartner(i):null,child:const Text('上位会社面談（1枠）')),if(a.replacementStage==PublicDemoReplacementStage.partnerPassed)FilledButton.tonal(onPressed:()=>replacementClient(i),child:const Text('客先面談（0枠）')),if(a.replacementStage==PublicDemoReplacementStage.partnerFailed||a.replacementStage==PublicDemoReplacementStage.clientFailed)FilledButton.tonal(onPressed:()=>ars(i,PublicDemoReplacementStage.selling),child:const Text('別案件へ')),if(a.replacementStage==PublicDemoReplacementStage.clientPassed)FilledButton(onPressed:()=>ars(i,PublicDemoReplacementStage.ordered),child:const Text('7月分を受注')),if(a.replacementStage==PublicDemoReplacementStage.ordered)const Text('7月：新案件参画予定')]])));}
 Widget ec(int i){final e=engineers[i];return Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(e.name,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:16)),badge(engineerStatus(e))]),const SizedBox(height:4),Text(e.summary),const SizedBox(height:8),if(e.stage==PublicDemoSalesStage.waiting)FilledButton(onPressed:()=>es(i,PublicDemoSalesStage.skillSheet),child:const Text('SkillSheet確認')),if(e.stage==PublicDemoSalesStage.skillSheet)FilledButton(onPressed:()=>es(i,PublicDemoSalesStage.selling),child:const Text('営業開始')),if(e.stage==PublicDemoSalesStage.selling)FilledButton(onPressed:()=>es(i,PublicDemoSalesStage.introduced),child:const Text('案件紹介')),if(e.stage==PublicDemoSalesStage.introduced)FilledButton(onPressed:s.salesRemaining>0?()=>ei(i,PublicDemoInterviewType.partner):null,child:const Text('上位会社面談')),if(e.stage==PublicDemoSalesStage.partnerInterviewPassed)FilledButton(onPressed:()=>ei(i,PublicDemoInterviewType.client),child:const Text('客先面談')),if(e.stage==PublicDemoSalesStage.clientInterviewPassed)FilledButton(onPressed:()=>es(i,PublicDemoSalesStage.ordered),child:const Text('受注')),if(e.stage==PublicDemoSalesStage.partnerInterviewFailed||e.stage==PublicDemoSalesStage.clientInterviewFailed)FilledButton(onPressed:()=>es(i,PublicDemoSalesStage.selling),child:const Text('再営業'))])));}
 Widget ac(int i){final a=applicants[i];return Card(child:Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[Text(a.name,style:const TextStyle(fontWeight:FontWeight.bold,fontSize:16)),badge(applicantStatus(a))]),const SizedBox(height:4),Text(a.resumeSummary),const SizedBox(height:8),if(a.stage==PublicDemoApplicantStage.applied)FilledButton(onPressed:()=>as(i,PublicDemoApplicantStage.resumeReviewed),child:const Text('経歴書確認')),if(a.stage==PublicDemoApplicantStage.resumeReviewed)FilledButton(onPressed:s.salesRemaining>0?()=>recruit(i):null,child:const Text('採用面談')),if(a.stage==PublicDemoApplicantStage.interviewed)...[Text('評価 ${a.interviewScore}'),FilledButton(onPressed:a.interviewScore>=60?()=>offer(i):null,child:const Text('合格・内定'))],if(a.stage==PublicDemoApplicantStage.offerAccepted)FilledButton(onPressed:()=>as(i,PublicDemoApplicantStage.preEntrySkillSheet),child:const Text('入社前SkillSheet')),if(a.stage==PublicDemoApplicantStage.preEntrySkillSheet)FilledButton(onPressed:()=>as(i,PublicDemoApplicantStage.preEntrySelling),child:const Text('入社前営業')),if(a.stage==PublicDemoApplicantStage.preEntrySelling)FilledButton(onPressed:()=>as(i,PublicDemoApplicantStage.preEntryIntroduced),child:const Text('案件紹介')),if(a.stage==PublicDemoApplicantStage.preEntryIntroduced)FilledButton(onPressed:s.salesRemaining>0?()=>pi(i):null,child:const Text('上位会社面談')),if(a.stage==PublicDemoApplicantStage.preEntryPartnerPassed)FilledButton(onPressed:()=>ci(i),child:const Text('客先面談')),if(a.stage==PublicDemoApplicantStage.preEntryClientPassed)FilledButton(onPressed:()=>as(i,PublicDemoApplicantStage.juneOrdered),child:const Text('6月受注'))])));}
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('S.E.S. Public Demo 0.1')),body:SafeArea(child:ListView(padding:const EdgeInsets.all(16),children:[Text('${s.month}月',style:Theme.of(c).textTheme.headlineMedium),dashboard(),if(s.month==4)...[for(var i=0;i<engineers.length;i++)ec(i),OutlinedButton(onPressed:april,child:const Text('4月終了→5月'))]else if(s.month==5)...[for(var i=0;i<applicants.length;i++)ac(i),OutlinedButton(onPressed:may,child:const Text('5月終了→6月'))]else if(s.month==6)...[Text('参画案件',style:Theme.of(c).textTheme.titleLarge),for(var i=0;i<assignments.length;i++)assignmentCard(i),OutlinedButton(onPressed:june,child:const Text('6月終了→7月'))]else...[Text('7月開始結果',style:Theme.of(c).textTheme.titleLarge),for(final a in assignments)ListTile(title:Text(a.engineerName),subtitle:Text(julyResult(a))),Text('参画 ${s.engineersAssigned}名 / 待機 ${s.engineersWaiting}名'),const Text('営業枠は4枠へリセットされました。')]])));
}
