import 'package:smile_enjoy_story/game/public_demo/public_demo_aggregate.dart';
import 'package:smile_enjoy_story/game/public_demo/public_demo_recruitment.dart';

/// CORE-GAMEPLAY Phase 4.5: [PublicDemoWorkflowState.initial] no longer
/// pre-seeds [publicDemoMayApplicants] (`app-01`/`app-02`) — a new game now
/// starts with zero applicants, and every applicant from that point on is
/// generated by [PublicDemoAggregate.recruit]. Several tests still want the
/// exact hand-authored `app-01`/`app-02` fixtures — not because production
/// game start still provides them, but because they are simulating a save
/// created before this fix (legacy save compatibility), where those two
/// applicants really were persisted. This helper reconstructs exactly that
/// scenario through the same [PublicDemoAggregate.fromJson] path a real save
/// load uses, splicing the legacy fixtures into the JSON envelope rather
/// than fabricating a production API to inject them directly.
PublicDemoAggregate withLegacyFoundingApplicants(PublicDemoAggregate aggregate) {
  final json = aggregate.toJson();
  final workflow = Map<String, dynamic>.from(json['workflow'] as Map);
  final existingApplicants = List<dynamic>.from(
    workflow['applicants'] as List,
  );
  workflow['applicants'] = [
    for (final applicant in publicDemoMayApplicants) applicant.toJson(),
    ...existingApplicants,
  ];
  return PublicDemoAggregate.fromJson({...json, 'workflow': workflow});
}
